version: "3.3"

services:
  backend-mongo:
    container_name: backend-mongo
    image: "bitnami/mongodb:4.0"
    volumes:
      - "backend-mongo_data:/bitnami"
    env_file:
      - .env
    expose:
      - "27017"


volumes: 
  backend-mongo_data:

networks:
  default:
    external:
      name: fullstack 
